[server]
port = 8081
servers = ['http://localhost:6483']
ns = 'http://example.com/doe-building#'
driver = 'modelica_driver.ModelicaJSONDriver'

[driver]
# lib_path='Buildings.Examples.VAVReheat'
# modelica_json_file='Guideline36'
# path='data/modelica/example-2'
# lib_path='Buildings.Examples.DualFanDualDuct'
# modelica_json_file='ClosedLoop'
# path='data/modelica/example-3'
lib_path='Buildings.Examples.HydronicHeating'
modelica_json_file='TwoRoomsWithStorage'
path='data/modelica/example-4'
